[project]
name = "vector-pengo-ice-block-sniping"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pygame",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]
