[project]
name = "vector-diamond-mine-puzzle-classic"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pygame",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
